### PR TITLE
Find empty inventory slot

### PR DESCRIPTION
**Pull request by tkjn**
Added an additional function to inventory api to identify the next available empty slot in the inventory

### CODE REVIEW

**Comment by tkjn** [comment]
@dezzak wanted to get your thoughts rather than just merging straight in ;)

**Comment by dezzak** [comment]
@tkjn I'm having issues on inventory:16 when using my existing excavate prog. Looking into it now. Could very easily be me being a lua noob though

**Comment by dezzak** [comment]
@tkjn found the issue. It's unrelated to the changes you made, but those changes highlighted it. I'll create a separate PR for that.
Good work chan!

**Comment by tkjn** [comment]
@dezzak yeh took me a bit to get my head around the difference between using : and . for method calls, think i'll stick to : where possible

**Pull request merged**
